const CURRENCIES={TWD:{name:'台幣',symbol:'NT$',flag:'🇹🇼'},KRW:{name:'韓元',symbol:'₩',flag:'🇰🇷'},PHP:{name:'披索',symbol:'₱',flag:'🇵🇭'},USD:{name:'美元',symbol:'US$',flag:'🇺🇸'}};
const API='https://api.frankfurter.dev/v2/rates?base=USD&quotes=TWD,KRW,PHP';
const state={from:localStorage.getItem('from')||'KRW',to:localStorage.getItem('to')||'TWD',current:'0',previous:null,operator:null,waiting:false,expression:'',rates:JSON.parse(localStorage.getItem('marketRates')||'null'),updatedAt:localStorage.getItem('ratesUpdatedAt')||'',custom:JSON.parse(localStorage.getItem('customRates')||'{}'),mode:localStorage.getItem('rateMode')||'market'};
let choosing='from';
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function fmt(n){if(!Number.isFinite(n))return '錯誤'; if(Math.abs(n)<1e-12)n=0; return new Intl.NumberFormat('en-US',{maximumFractionDigits:8}).format(n)}
function symbol(c){return CURRENCIES[c].symbol}
function setCurrencies(){['baseCustom','quoteCustom'].forEach(id=>{$('#'+id).innerHTML=Object.keys(CURRENCIES).map(c=>`<option value="${c}">${CURRENCIES[c].flag} ${c} ${CURRENCIES[c].name}</option>`).join('')});$('#baseCustom').value='USD';$('#quoteCustom').value='PHP'}
function pairKey(a,b){return `${a}_${b}`}
function getRate(a,b){if(a===b)return 1; if(state.mode==='custom'){const d=state.custom[pairKey(a,b)];if(d)return d;const r=state.custom[pairKey(b,a)];if(r)return 1/r;return null} if(!state.rates)return null; const usd=state.rates; const ra=a==='USD'?1:usd[a]; const rb=b==='USD'?1:usd[b]; return ra&&rb?rb/ra:null}
function render(){const from=CURRENCIES[state.from],to=CURRENCIES[state.to];$('#fromBtn').textContent=`${from.flag} ${state.from} ${from.name}`;$('#toBtn').textContent=`${to.flag} ${state.to} ${to.name}`;$('#amount').textContent=fmt(Number(state.current));$('#expression').textContent=state.expression; const rate=getRate(state.from,state.to); if(rate==null){$('#converted').textContent='—';$('#rateText').textContent=state.mode==='custom'?'尚未設定我的匯率':'尚未取得匯率'}else{$('#converted').textContent=`${symbol(state.to)}${fmt(Number(state.current)*rate)}`;$('#rateText').textContent=`1 ${state.from} = ${fmt(rate)} ${state.to}`}$('#modeBtn').textContent=state.mode==='market'?'市場匯率':'我的匯率';renderQuick();renderCustom();}
function renderQuick(){const values={TWD:[1000,3000,5000],KRW:[10000,50000,100000],PHP:[500,1000,2000],USD:[10,50,100]}[state.from];$('#quick').innerHTML=values.map(v=>`<button data-quick="${v}">${symbol(state.from)}${fmt(v)}</button>`).join('')}
function inputNum(v){if(state.waiting){state.current='0';state.waiting=false} if(v==='.'&&state.current.includes('.'))return; if(state.current==='0'&&v!=='.')state.current=v;else state.current+=v;render()}
function calculate(){const a=Number(state.previous),b=Number(state.current);if(state.operator===null)return b;let r; if(state.operator==='+')r=a+b;if(state.operator==='-')r=a-b;if(state.operator==='*')r=a*b;if(state.operator==='/')r=b===0?NaN:a/b;state.current=String(r);state.previous=null;state.operator=null;state.waiting=true;state.expression='';return r}
function setOperator(op){if(state.operator!==null&&!state.waiting)calculate();state.previous=Number(state.current);state.operator=op;state.waiting=true;state.expression=`${fmt(state.previous)} ${op==='*'?'×':op==='/'?'÷':op==='-'?'−':'+'}`;render()}
function equals(){if(state.operator!==null)calculate();state.expression='';render()}
$$('.keys button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.num!==undefined)inputNum(b.dataset.num);else if(b.dataset.op)setOperator(b.dataset.op);else if(b.dataset.action==='clear'){Object.assign(state,{current:'0',previous:null,operator:null,waiting:false,expression:''});render()}else if(b.dataset.action==='sign'){state.current=String(Number(state.current)*-1);render()}else if(b.dataset.action==='percent'){state.current=String(Number(state.current)/100);render()}else if(b.dataset.action==='equals')equals()}));
$('#quick').addEventListener('click',e=>{const b=e.target.closest('[data-quick]');if(!b)return;state.current=b.dataset.quick;state.previous=null;state.operator=null;state.waiting=false;state.expression='';render()});
$('#fromBtn').onclick=()=>openCurrency('from');$('#toBtn').onclick=()=>openCurrency('to');$('#swapBtn').onclick=()=>{[state.from,state.to]=[state.to,state.from];localStorage.setItem('from',state.from);localStorage.setItem('to',state.to);render()};
function openCurrency(which){choosing=which;$('#currencyTitle').textContent=which==='from'?'選擇原幣別':'選擇換算幣別';$('#currencyList').innerHTML=Object.entries(CURRENCIES).map(([c,x])=>`<button class="currency-option" data-currency="${c}">${x.flag} ${c} ${x.name}</button>`).join('');$('#currencyModal').classList.remove('hidden')}
$('#currencyList').addEventListener('click',e=>{const b=e.target.closest('[data-currency]');if(!b)return;if(choosing==='from')state.from=b.dataset.currency;else state.to=b.dataset.currency;localStorage.setItem('from',state.from);localStorage.setItem('to',state.to);$('#currencyModal').classList.add('hidden');render()});
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('#settingsBtn').onclick=()=>$('#settingsModal').classList.remove('hidden');
$('#modeBtn').onclick=()=>{state.mode=state.mode==='market'?'custom':'market';localStorage.setItem('rateMode',state.mode);render()};
$('#saveCustom').onclick=()=>{const a=$('#baseCustom').value,b=$('#quoteCustom').value,r=Number($('#customRate').value);if(a===b||!r||r<=0){alert('請確認幣別與匯率');return}state.custom[pairKey(a,b)]=r;localStorage.setItem('customRates',JSON.stringify(state.custom));state.mode='custom';localStorage.setItem('rateMode','custom');$('#customRate').value='';render()};
$('#customList').addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;delete state.custom[b.dataset.delete];localStorage.setItem('customRates',JSON.stringify(state.custom));render()});$('#clearCustom').onclick=()=>{state.custom={};localStorage.setItem('customRates','{}');render()};
function renderCustom(){const entries=Object.entries(state.custom);$('#customList').innerHTML=entries.length?entries.map(([k,v])=>{const[a,b]=k.split('_');return `<div class="custom-item"><span>1 ${a} = ${fmt(v)} ${b}</span><button class="delete" data-delete="${k}">刪除</button></div>`}).join(''):'<div class="empty">還沒有設定我的匯率</div>'}
async function fetchRates(){try{const res=await fetch(API,{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json();const rates={USD:1};if(Array.isArray(data))data.forEach(x=>{if(x.quote&&x.rate)rates[x.quote]=x.rate});else if(data.rates)Object.assign(rates,data.rates);if(!rates.TWD||!rates.KRW||!rates.PHP)throw new Error();state.rates=rates;state.updatedAt=new Date().toISOString();localStorage.setItem('marketRates',JSON.stringify(rates));localStorage.setItem('ratesUpdatedAt',state.updatedAt);$('#status').textContent='● 線上｜匯率已更新';$('#updated').textContent='市場匯率已更新；離線時會使用上次成功儲存的匯率。';render()}catch(e){if(state.rates){$('#status').textContent='● 離線｜使用上次匯率';$('#updated').textContent=`離線模式｜上次更新：${state.updatedAt?new Date(state.updatedAt).toLocaleString('zh-TW'): '未知'}`}else{$('#status').textContent='● 離線｜尚無市場匯率';$('#updated').textContent='目前沒有網路，也沒有之前儲存的市場匯率；我的匯率仍可離線使用。'}render()}}
window.addEventListener('online',fetchRates);window.addEventListener('keydown',e=>{if(e.key>='0'&&e.key<='9'||e.key==='.')inputNum(e.key);else if(['+','-','*','/'].includes(e.key))setOperator(e.key);else if(e.key==='Enter'||e.key==='=')equals();else if(e.key==='Escape'){Object.assign(state,{current:'0',previous:null,operator:null,waiting:false,expression:''});render()}});
setCurrencies();render();fetchRates();
